###### Translations here #######

# SEO
title: "PapaKoala: Atividades de Estimulação Precoce para Bebês Fáceis de Fazer"
tagline: Atividades de Estimulação Precoce para Bebês Fáceis de Fazer
description: Atividades de Estimulação Precoce para Bebês para promover o desenvolvimento do cérebro, fornecer experiências sensoriais precoces e construir um senso de confiança.
# page title
page_title: "Nutrir seu Pequeno Gênio: Descubra a Jornada de Estimulação Precoce da PapaKoala"
app_name: "PapaKoala: Desenvolvimento do Recém-Nascido"
app_price: Assinatura
app_subtitle: Embarque em uma jornada de inteligência e vínculo com o PapaKoala para bebês de 0 a 1 ano.
app_description: "Os primeiros anos são uma janela de oportunidade excepcional para o desenvolvimento do cérebro de um bebê. Este é o momento ideal para acender seu potencial intelectual e estabelecer a base para uma aprendizagem ao longo da vida. \nO PapaKoala, seu guia pessoal de estimulação precoce, capacita você a nutrir o crescimento cognitivo do seu pequeno e criar uma conexão emocional profunda com ele."

# Feature List Edit, add or remove features to be presented.
features:
  - title: Desbloqueie o Poder da Estimulação Precoce
    description: Mergulhe seu bebê em um mundo de experiências estimulantes que promovem seu desenvolvimento cerebral e despertam seus sentidos. As atividades cuidadosamente selecionadas do PapaKoala, orientadas por pesquisas de desenvolvimento especializadas, apresentam seu pequeno a uma sinfonia de imagens, sons e toque, estimulando suas vias neurais e estabelecendo as bases para o sucesso futuro.
    fontawesome_icon_name: baby

  - title: Experimente a Alegria da Aprendizagem Interativa
    description: Diga adeus aos exercícios monótonos e abrace a natureza divertida e envolvente das atividades interativas do PapaKoala. Nossos tutoriais em vídeo fornecem orientação clara e tornam a aprendizagem uma experiência agradável para pais e bebês.
    fontawesome_icon_name: brain

  - title: Nutra um Vínculo de Amor e Confiança
    description: A estimulação precoce vai além do desenvolvimento cognitivo; trata-se de criar um vínculo seguro e amoroso entre você e seu bebê. As atividades do PapaKoala enfatizam o toque, a forma mais fundamental de interação com o bebê, promovendo confiança, segurança e uma profunda conexão emocional.
    fontawesome_icon_name: heart



############## end of translations block #####





# App Info
ios_app_id                                : 1540490806                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
spanish_page_link                         : https://es.papakoala.com                                                                                      
japan_page_link                           : https://jap.papakoala.com
english_page_link                         : https://papakoala.com  
chinese_page_link                         : https://cn.papakoala.com
german_page_link                          : https://ger.papakoala.com
southkorea_page_link                      : https://kor.papakoala.com
french_page_link                          : https://fr.papakoala.com
italian_page_link                         : https://it.papakoala.com
hindi_page_link                           : https://hi.papakoala.com
portuguese_page_link                      : https://pt.papakoala.com
brazil_page_link                          : https://ptbra.papakoala.com

app_icon                                  :                      # assets/appicon.png  Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.


enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : PapaKoala                                
your_link                                 : https://papakoala.com                     
your_city                                 :                              
email_address                             : hello@papakoala.com
facebook_username                         :                                           
instagram_username                        : papakoala_app
twitter_username                          : 
github_username                           : 
youtube_username                          : 




# Theme Settings
topbar_color                              : "#6EC8FF"
topbar_transparency                       : 0.4
topbar_title_color                        : "#444B54"

cover_image                               : assets/header_lowres.jpg                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.6

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#FFEAC1"

app_title_color                           : "#393e44"
app_price_color                           : "#FFFFFF"
app_description_color                     : "#ffffff"

app_language_color                        : "#FFEAC1"

feature_title_color                       : "#FFEAC1"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#FA6694"

social_icons_foreground_color             : "#BF82EC"
social_icons_background_color             : "#FFFFFF"

footer_text_color                         : "#000000"




# Google services
google_analytics: G-D89JL3TSP6




# url: papakoala.com




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

plugins:
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
